import { useState } from "react";
import { Card } from "../../components/ui/card";
import { Input } from "../../components/ui/input";
import { Button } from "../../components/ui/button";
import { Textarea } from "../../components/ui/textarea";
import { Search, Sparkles, Copy, Bookmark } from "lucide-react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "../../components/ui/tabs";

export default function ProfessionalResearch() {
  const [query, setQuery] = useState("");
  const [response, setResponse] = useState("");
  const [isSearching, setIsSearching] = useState(false);
  const [savedResearch, setSavedResearch] = useState<Array<{ title: string; content: string }>>([]);

  const handleResearch = () => {
    if (!query.trim()) return;
    setIsSearching(true);

    setTimeout(() => {
      setResponse(`# Research Results for: "${query}"

## Overview
This is a comprehensive research response generated by AI. In a production environment, this would:
- Search through multiple knowledge bases
- Analyze academic papers and articles
- Provide cited sources
- Offer detailed insights and analysis

## Key Findings
1. **Finding 1**: Detailed explanation with supporting evidence
2. **Finding 2**: Analysis and implications
3. **Finding 3**: Relevant data and statistics

## Detailed Analysis
Lorem ipsum dolor sit amet, consectetur adipiscing elit. In a production app, this would contain deep, contextual research based on your query. The AI would analyze multiple sources and provide comprehensive insights.

## Sources & References
- [Source 1]: Academic paper or article
- [Source 2]: Research database
- [Source 3]: Industry report

## Related Topics
- Topic 1 related to your research
- Topic 2 for further exploration
- Topic 3 for comprehensive understanding`);
      setIsSearching(false);
    }, 2000);
  };

  const saveResearch = () => {
    if (response) {
      setSavedResearch([...savedResearch, { title: query, content: response }]);
    }
  };

  return (
    <div className="h-screen flex flex-col bg-gray-50 dark:bg-gray-900">
      {/* Header */}
      <div className="border-b border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-800 px-6 py-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-lg bg-gradient-to-r from-orange-500 to-orange-600 flex items-center justify-center">
            <Search className="h-5 w-5 text-white" />
          </div>
          <div>
            <h1 className="text-xl font-semibold text-gray-900 dark:text-white">AI Research Assistant</h1>
            <p className="text-sm text-gray-500 dark:text-gray-400">Deep research on any topic</p>
          </div>
        </div>
      </div>

      <div className="flex-1 overflow-hidden">
        <Tabs defaultValue="research" className="h-full flex flex-col">
          <div className="px-6 pt-4">
            <TabsList>
              <TabsTrigger value="research">Research</TabsTrigger>
              <TabsTrigger value="saved">Saved ({savedResearch.length})</TabsTrigger>
            </TabsList>
          </div>

          <TabsContent value="research" className="flex-1 overflow-auto px-6 pb-6">
            <div className="max-w-4xl mx-auto space-y-6">
              {/* Search Input */}
              <Card className="p-4">
                <div className="space-y-4">
                  <Input
                    placeholder="What would you like to research?"
                    value={query}
                    onChange={(e) => setQuery(e.target.value)}
                    onKeyPress={(e) => e.key === "Enter" && handleResearch()}
                    className="text-lg"
                  />
                  <Button onClick={handleResearch} disabled={isSearching || !query.trim()} className="w-full" size="lg">
                    {isSearching ? (
                      <>Researching...</>
                    ) : (
                      <>
                        <Search className="mr-2 h-4 w-4" />
                        Start Research
                      </>
                    )}
                  </Button>
                </div>
              </Card>

              {/* Research Results */}
              {response && (
                <Card className="p-6">
                  <div className="flex justify-between items-start mb-4">
                    <h2 className="text-xl font-semibold">Research Results</h2>
                    <div className="flex gap-2">
                      <Button size="sm" variant="outline" onClick={() => navigator.clipboard.writeText(response)}>
                        <Copy className="h-4 w-4 mr-1" />
                        Copy
                      </Button>
                      <Button size="sm" variant="outline" onClick={saveResearch}>
                        <Bookmark className="h-4 w-4 mr-1" />
                        Save
                      </Button>
                    </div>
                  </div>
                  <Textarea value={response} onChange={(e) => setResponse(e.target.value)} rows={20} className="font-mono text-sm" />
                </Card>
              )}

              {!response && !isSearching && (
                <div className="text-center py-20 text-gray-400">
                  <Search className="h-16 w-16 mx-auto mb-4 opacity-20" />
                  <p className="text-lg">Enter a research topic to get started</p>
                  <p className="text-sm mt-2">Ask about anything - science, technology, business, history, and more</p>
                </div>
              )}
            </div>
          </TabsContent>

          <TabsContent value="saved" className="flex-1 overflow-auto px-6 pb-6">
            <div className="max-w-4xl mx-auto space-y-4">
              {savedResearch.length === 0 ? (
                <div className="text-center py-20 text-gray-400">
                  <Bookmark className="h-16 w-16 mx-auto mb-4 opacity-20" />
                  <p>No saved research yet</p>
                </div>
              ) : (
                savedResearch.map((item, index) => (
                  <Card key={index} className="p-6">
                    <h3 className="font-semibold text-lg mb-2">{item.title}</h3>
                    <p className="text-sm text-gray-600 dark:text-gray-400 line-clamp-3">{item.content}</p>
                    <Button size="sm" variant="outline" className="mt-4">
                      View Full Research
                    </Button>
                  </Card>
                ))
              )}
            </div>
          </TabsContent>
        </Tabs>
      </div>
    </div>
  );
}
